services:
  monitor-sensors-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitor-sensors-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-monitor-sensors:5432/sensors_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_PASSWORD=postgres
      - JWT_SECRET=DtLln0ulGdXd9LO9U3BEgXRV6tgloi2g
      - INTERNAL_API_KEY=7F01A8F1234567890123456789ABCDEF
    restart: unless-stopped
    ports:
      - "18080:8080"
    depends_on:
      - postgres-monitor-sensors

  sensors-statistics-service:
    image: mkrutalevich/sensors-statistics:latest
    container_name: sensors-statistics-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-sensors-statistics:5432/statistics_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_LIQUIBASE_PASSWORD=postgres
      - INTERNAL_API_KEY=7F01A8F1234567890123456789ABCDEF
      - MONITOR_SENSORS_URL=http://monitor-sensors-service:8080
    ports:
      - "18081:8080"
    depends_on:
      - postgres-sensors-statistics
      - monitor-sensors-service

  postgres-monitor-sensors:
    image: postgres:15
    container_name: postgres-monitor-sensors
    environment:
      POSTGRES_DB: sensors_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - monitor-sensors-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  postgres-sensors-statistics:
    image: postgres:15
    container_name: postgres-sensors-statistics
    environment:
      POSTGRES_DB: statistics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - sensor-statistics-data:/var/lib/postgresql/data
    ports:
      - "15433:5432"

volumes:
  monitor-sensors-data:
  sensor-statistics-data:
