server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: false
    open-in-view: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

jwt:
  secret: ${JWT_SECRET}
  access:
    duration: PT20M
  refresh:
    duration: P3D

internal:
  api-key: ${INTERNAL_API_KEY}